server.port: 8080
logging.level.springframework.web: DEBUG

etherscan.url: http://api.etherscan.io
cryptocompare.url: https://min-api.cryptocompare.com/

mongo:
 mainDatabase: invoice
 metricsDatabase: invoices

earliest.query.month: 200001